### ISSUE TITLE
"ValueError: Malformed tree: no root" in hopsparser/deptree.py during prediction

### ISSUE THREAD

**Issue by ziqianPeng** [hopsparser/hopsparser#76]
Hello,

I tried to use hopsparser to train parser for Zaar and predict other Zaar files, while during the prediction, a "ValueError: Malformed tree: no root " occured.

The **config** I used is the same as [flaubert.yaml](https://github.com/hopsparser/hopsparser/blob/main/examples/flaubert.yaml) with model = [bert-base-multilingual-uncased](https://huggingface.co/bert-base-multilingual-uncased)
The **training set** is [SAY_BC_CONV_01.conllu](https://github.com/surfacesyntacticud/SUD_Zaar_Autogramm/blob/master/CORPUS/SAY_BC_CONV_01.conllu) and [SAY_BC_CONV_02.conllu](https://github.com/surfacesyntacticud/SUD_Zaar_Autogramm/blob/master/CORPUS/SAY_BC_CONV_02.conllu) 

the **files to parse** are other files in this page 
[https://github.com/surfacesyntacticud/SUD_Zaar_Autogramm/tree/master/CORPUS](https://github.com/surfacesyntacticud/SUD_Zaar_Autogramm/tree/master/CORPUS) 

During prediction, an empty file is returned for the file _'SAY_BC_INT_01_Religion.conllu''_ and _'SAY_BC_INT_05_Morals.conllu'_. When I tried to parse sentence by sentence, hopsparser can parse some sentences in both file above.
For the two files, I got 8  "ValueError: Malformed tree: no root " as below:
```

Traceback (most recent call last):
  File "/mnt/beegfs/home/peng/miniconda3/bin/hopsparser", line 8, in <module>
    sys.exit(cli())
  File "/mnt/beegfs/home/peng/miniconda3/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/beegfs/home/peng/miniconda3/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/mnt/beegfs/home/peng/miniconda3/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/beegfs/home/peng/miniconda3/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/beegfs/home/peng/miniconda3/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/beegfs/home/peng/miniconda3/lib/python3.9/site-packages/hopsparser/main.py", line 80, in parse
    parser.parse(
  File "/mnt/beegfs/home/peng/miniconda3/lib/python3.9/site-packages/hopsparser/parser.py", line 1151, in parse
    for tree in parser.parse(
  File "/mnt/beegfs/home/peng/miniconda3/lib/python3.9/site-packages/hopsparser/parser.py", line 855, in parse
    yield from self.batched_predict(batches, greedy=False)
  File "/mnt/beegfs/home/peng/miniconda3/lib/python3.9/site-packages/hopsparser/parser.py", line 740, in batched_predict
    for batch in batch_lst:
  File "/mnt/beegfs/home/peng/miniconda3/lib/python3.9/site-packages/hopsparser/parser.py", line 851, in <genexpr>
    batches = (
  File "/mnt/beegfs/home/peng/miniconda3/lib/python3.9/site-packages/boltons/iterutils.py", line 362, in chunked_iter
    cur_chunk = list(itertools.islice(src_iter, size))
  File "/mnt/beegfs/home/peng/miniconda3/lib/python3.9/site-packages/hopsparser/deptree.py", line 201, in read_conll
    yield cls.from_conllu(current_tree_lines)
  File "/mnt/beegfs/home/peng/miniconda3/lib/python3.9/site-packages/hopsparser/deptree.py", line 163, in from_conllu
    return cls(
  File "/mnt/beegfs/home/peng/miniconda3/lib/python3.9/site-packages/hopsparser/deptree.py", line 59, in __init__
    raise ValueError("Malformed tree: no root")
ValueError: Malformed tree: no root

```

I also discovered that the parsed result [SAY_BC_INT_03_Calendar.conllu](https://github.com/surfacesyntacticud/SUD_Zaar_Autogramm/blob/master/CORPUS/SAY_BC_INT_03_Calendar.conllu) are not complete, the model only parsed several sentences and produce the file.

**Comment by LoicGrobol** [comment]
Thanks for the report Ziqian! Indeed we never tried parsing files already in CoNLL-U format but without complete syntax annotations yet. Can you try to install from the `partial-supervision` branch (with `pip install -U git+https://github.com/hopsparser/hopsparser@partial-supervision`) and see if the problem is still present ?

**Comment by ziqianPeng** [comment]
sorry I just saw your reply, thanks for the update! 
I tried with the partial-supervision branch, some prediction changed, while hopsparser still cannot parse the same sentences and still return empty file for 'SAY_BC_INT_01_Religion.conllu'' and 'SAY_BC_INT_05_Morals.conllu'.

**Comment by LoicGrobol** [comment]
Hi @ziqianPeng, the issue is that the files you are trying to parse have syntactic annotations (head) that are

- Complete (every word has a head)
- Inconsistent: there are trees with no root (an thus with cycles), see for instance

```conllu
# sent_id = SAY_BC_INT_01_Religion_017-019
# speaker_id = SP1
# sound_url = https://corporan.huma-num.fr/Archives/media/SAY/WAV/SAY_BC_INT_01_Religion.WAV
# sent_timecode = 20472, 25200
# text = lóːkaʧí -ês báː màː kə́ːm mə̀ fi sə́ŋwaːrí hŋ́ séː deː mì nə məːri //
# text_ortho = lóːkaʧês bàː màː kə́ːm mə̀ fì sə́ŋwaːrí hŋ́ séː deː mì nə məːri //
# text_en =  at that time, we could not... be religious chief  unless we were young.
1	lóːkaʧí-ês	lóːkaʧí	NOUN	_	_	4	dislocated	_	AlignBegin=20472|AlignEnd=20844|GE=time[DEF]|Gloss=time|MGloss=timeDEF|MSeg=lóːkaʧí-ês|nWord=1|RX=[N][ART]|wordform=lóːkaʧí
2	báː	báː	PART	_	Polarity=Neg	1	discourse	_	AlignBegin=20844|AlignEnd=21216|GE=[NEG1]|Gloss=NEG1|nWord=2|RX=[PTCL].[NEG]
3	màː	màː	AUX	_	Aspect=Perf|Number=Plur|Person=1	1	det	_	AlignBegin=21216|AlignEnd=21588|GE=[1PL].[CPL]|Gloss=1PL.CPL|nWord=3|RX=[PNTAM]
4	kə́ːm	kə́ːm	VERB	_	_	3	comp:aux	_	AlignBegin=21588|AlignEnd=21960|GE=can|Gloss=can|nWord=4|RX=[V]
5	mə̀	mə̀	AUX	_	Mood=Sub|Number=Plur|Person=1	4	comp:aux	_	AlignBegin=22860|AlignEnd=23065|GE=[1PL].[SBJV]|Gloss=1PL.SBJV|nWord=5|RX=[PNTAM]
6	fi	fi	VERB	_	_	5	comp:aux	_	AlignBegin=23065|AlignEnd=23270|GE=do|Gloss=do|nWord=6|RX=[V]
7	sə́ŋwaːrí	sə́ŋwaːrí	NOUN	_	_	6	comp:obj	_	AlignBegin=23270|AlignEnd=23475|GE=chief_priest|Gloss=chief_priest|nWord=7|RX=[N]
8	hŋ́	hŋ́	PART	_	Polarity=Neg	6	mod	_	AlignBegin=23475|AlignEnd=23680|GE=[NEG2]|Gloss=NEG2|nWord=8|RX=[PTCL].[NEG]
9	séː	séː	SCONJ	_	_	11	cc	_	AlignBegin=24280|AlignEnd=24433|GE=except|Gloss=except|nWord=9|RX=[CONJ]
10	deː	deː	ADV	_	_	11	mod	_	AlignBegin=24433|AlignEnd=24586|GE=anyway|Gloss=anyway|nWord=10|RX=[ADV]
11	mì	mì	VERB	_	Number=Plur|Person=1|PronType=Prs	4	conj:coord	_	AlignBegin=24586|AlignEnd=24739|GE=[1PL].[be]|Gloss=1PL.be|nWord=11|RX=[PRO].[V*]
12	nə	nə	PART	_	VerbType=Cop	11	comp:aux	_	AlignBegin=24739|AlignEnd=24892|GE=[COP1]|Gloss=be|nWord=12|RX=[PTCL].[SYNT]
13	məːri	məːri	NOUN	_	Number=Plur	6	comp:goal	_	AlignBegin=24892|AlignEnd=25045|GE=children|Gloss=children|nWord=13|RX=[N].[PL]
14	//	//	PUNCT	_	_	11	punct	_	AlignBegin=25045|AlignEnd=25200|GE=[//]|Gloss=PUNCT|nWord=14
```

Dealing with that kind of data is something that *could* be supported in HOPS, but it's very low priority for now, so your best bet is probably to just zero out these annotations before parsing (just put `_` for the HEAD column).
