### ISSUE TITLE
Empty node error when parsing CONLLU files

### ISSUE THREAD

**Issue by RomanCast** [hopsparser/hopsparser#80]
Hello,

First of all thanks for this super useful library.

When using it on UD_Arabic-PADT I got the following error : 

```
Traceback (most recent call last):
  File "/gpfswork/rech/rcy/ulz63oj/miniconda3/envs/artificial_data/bin/hopsparser", line 8, in <module>
    sys.exit(cli())
  File "/gpfswork/rech/rcy/ulz63oj/miniconda3/envs/artificial_data/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/gpfswork/rech/rcy/ulz63oj/miniconda3/envs/artificial_data/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/gpfswork/rech/rcy/ulz63oj/miniconda3/envs/artificial_data/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/gpfswork/rech/rcy/ulz63oj/miniconda3/envs/artificial_data/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/gpfswork/rech/rcy/ulz63oj/miniconda3/envs/artificial_data/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/gpfsdswork/projects/rech/rcy/ulz63oj/code/hopsparser/hopsparser/main.py", line 157, in train
    parser.train(
  File "/gpfsdswork/projects/rech/rcy/ulz63oj/code/hopsparser/hopsparser/parser.py", line 1105, in train
    traintrees = list(
  File "/gpfsdswork/projects/rech/rcy/ulz63oj/code/hopsparser/hopsparser/deptree.py", line 228, in read_conll
    yield cls.from_conllu(current_tree_lines)
  File "/gpfsdswork/projects/rech/rcy/ulz63oj/code/hopsparser/hopsparser/deptree.py", line 176, in from_conllu
    identifier=int(cast(str, processed_row[0])),
ValueError: invalid literal for int() with base 10: '27.1'
```

It seems that 27.1 is a valid ID that corresponds to an [empty node](https://universaldependencies.org/format.html#words-tokens-and-empty-nodes), but it is not handled by the parser in `deptree.py`:

https://github.com/hopsparser/hopsparser/blob/e3242340a2f1d794d1894b5cda3cdb1f59cbcd62/hopsparser/deptree.py#L164-L186

I may be mistaken, but I think that simply ignoring it is a valid fix as these lines will not be used for dependency parsing : 

```python
if "." in row[0]:
    continue
```

Thank you.

**Comment by LoicGrobol** [comment]
I actually fixed this long ago (in b7aa2484d265c2e1e2f41e387dc2d7743d715fd9) but forgot to close the issue.
